name: signal-desktop
base: core18
adopt-info: signal-desktop
summary: Signal Desktop
description: |
  Private messaging from your desktop.

grade: stable
confinement: strict

architectures: 
  - build-on: amd64

parts:
  signal-desktop:
    plugin: nil
    #source: https://updates.signal.org/desktop/apt/pool/main/s/signal-desktop/signal-desktop_1.30.0_amd64.deb
    build-packages:
      - wget
      - jq
      - dpkg
      - git
    stage-packages:
      - libxss1
      - libnspr4
      - libnss3
    override-build: |
      set -xeu
      echo "Get GitHub releases..."
      wget --quiet https://api.github.com/repos/signalapp/Signal-Desktop/releases -O releases.json
      # Get the version from the tag_name and the download URL.
      VERSION=$(jq . releases.json | grep tag_name | grep -v beta | head -n 1 | cut -d'"' -f4 | tr -d 'v')
      DEB_URL="https://updates.signal.org/desktop/apt/pool/main/s/signal-desktop/signal-desktop_"$VERSION"_amd64.deb"
      wget --quiet $DEB_URL -O signal.deb
      dpkg-deb -x signal.deb $SNAPCRAFT_PART_INSTALL/
      rm signal.deb releases.json
      sed -i 's|Icon=signal-desktop|Icon=${SNAP}/usr/share/icons/hicolor/512x512/apps/signal-desktop.png|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/signal-desktop.desktop
      snapcraftctl set-version "$VERSION"
    prime:
      - -opt/Signal/crome-sandbox

apps:
  signal-desktop:
    extensions: [gnome-3-28]
    desktop: usr/share/applications/signal-desktop.desktop
    command: opt/Signal/signal-desktop --use-tray-icon --no-sandbox
    plugs:
      - desktop
      - desktop-legacy
      - home
      - x11
      - wayland
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
      - removable-media
    environment:
      DISABLE_WAYLAND: '1'
      GTK_USE_PORTAL: "1"
      TMPDIR: $XDG_RUNTIME_DIR
      PATH: '$SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH'
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
      LD_LIBRARY_PATH: '$SNAP_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib:$SNAP/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu'
      WAYLAND_DISPLAY: no-display
      XDG_CURRENT_DESKTOP: Unity
